# Generated by Django 6.0.7 on 2026-08-01 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_owner_alter_project_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participating_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
