# Generated by Django 6.0.7 on 2026-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hex_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True),
        ),
    ]
